const REQUESTMESSAGE = {
  ROLE_INVALID: "ROLE_INVALID",
  EMAIL_REGISTER_INVALID: "EMAIL_REGISTER_INVALID",
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  BAD_REQUEST: "BAD_REQUEST",
  UNAUTHORIZE: "UNAUTHORIZE",
};

module.exports = REQUESTMESSAGE;
